# Generated by Django 5.2.5 on 2026-01-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_disease', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('image', models.ImageField(upload_to='disease_images/')),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('image_link', models.URLField(blank=True, max_length=500)),
                ('import_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
