# Generated by Django 5.2.5 on 2026-01-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_router', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasedetection',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='diseasedetection',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
